//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMediaDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string StorageLocation { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Genre { get; set; }
        public Nullable<int> RunTimeMinutes { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public string HomePage { get; set; }
        public string Overview { get; set; }
        public string CastDetails { get; set; }
    }
}
